# Generated by Django 3.0.4 on 2020-03-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_users_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachers',
            name='category',
            field=models.CharField(default='Enter Your Interests', max_length=100),
        ),
    ]
