# Generated by Django 3.0.4 on 2020-03-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='table_of_content',
            field=models.TextField(default='Enter the Topics which will be taught'),
        ),
    ]
