# Generated by Django 3.0.4 on 2020-03-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_table_of_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='image',
            field=models.ImageField(default='default-user.jpg', upload_to='user_pics'),
        ),
    ]
