# Generated by Django 2.2.6 on 2020-03-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_teachers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='category',
            field=models.CharField(default='Enter Your Interests', max_length=30),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
