# Generated by Django 2.2.6 on 2020-03-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200325_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
