# Generated by Django 3.0.4 on 2020-03-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200325_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='profile_pic',
            field=models.ImageField(default='user_pics/default-user.png', upload_to='user_pics'),
        ),
    ]
