# Generated by Django 3.0.4 on 2020-03-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200325_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='course_pics/default.jpg', upload_to='course_pics'),
        ),
    ]
