# Generated by Django 2.2.6 on 2020-03-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200325_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(default='video_pics/default.jpg', upload_to='video_pics'),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_number',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
