# Generated by Django 3.0.4 on 2020-03-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200330_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_file',
            field=models.FileField(default='course_videos/life_hacks.mp4', upload_to='course_videos/'),
        ),
    ]
