# Generated by Django 3.0.4 on 2020-04-01 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_videos_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='course_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='video_id',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='courses.Videos'),
        ),
    ]
