# Generated by Django 2.2.6 on 2020-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_init_test', '0002_auto_20200316_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lname',
            field=models.CharField(default='sike', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default='0000000000'),
        ),
    ]
